# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Our Wedding"
#email: ""
description: >- # this means to ignore newlines until "baseurl:"
  We look forward to celebrating with you!
 
baseurl: "" #website" # when publishing to web use "website"; o/w ""
url: "" # when demo'ing on local machine use "localhost:4000:; ow ""
twitter_username: "ravedawwg"
github_username:  ravedawg


# adding categories functionality sans plugin
collections:
  category:
    output: true
    
# allow posts dated in the "future" to be true
future: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# enable google analytics
google_analytics: UA-NNNNNNNN-N

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
